__type__ = "function"
__name__ = "test_func1"

[__globals__]
math = "module"
a = 123

[__code__]
co_argcount = 1
co_posonlyargcount = 0
co_knowlyargcount = 0
co_nlocals = 2
co_stacksize = 4
co_flags = 67
co_code = [ 100, 1, 125, 1, 116, 0, 160, 1, 124, 0, 116, 2, 20, 0, 124, 1, 20, 0, 161, 1, 83, 0,]
co_consts = [ 91, 10, 9, 110, 117, 108, 108, 44, 10, 9, 49, 50, 51, 10, 93,]
co_names = [ "math", "sin", "a",]
co_varnames = [ "x", "b",]
co_filename = "/home/kraken/PycharmProjects/Lab2/test_objects/test_functions.py"
co_name = "test_func1"
co_firstlineno = 7
co_lnotab = [ 0, 1, 4, 1,]
co_freevars = []
co_cellvars = []
